const { FULL_HD, AUDIO_ICON, VIDEO_ICON, PREF_FIELDS } = require("./general");

const { YEARTEXT, JW_API, JWPUB_API, REPO_URL, FFMPEG_VERSION } = require("./endpoints");

module.exports = {
  YEARTEXT, JW_API, JWPUB_API, REPO_URL, FFMPEG_VERSION, FULL_HD, AUDIO_ICON, VIDEO_ICON, PREF_FIELDS
};
