pull_request_rules:
  - name: Automatically merge Dependabot PRs
    conditions:
      - and:
          - or:
              - author = dependabot[bot]
              - author = github-actions[bot]
          - title ~= ^chore\(deps(?:-dev)*\). bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      update:
      merge:
        method: squash

  - name: Automatically merge Crowdin PRs
    conditions:
      - and:
          - author = sircharlo
          - title ~= new translations
    actions:
      update:
      merge:
        method: squash
