#pull_request_rules:
#  - name: Automatically merge Dependabot PRs (minor/patch only, including -dev and prereleases)
#    conditions:
#      - author = dependabot[bot]
#      - title ~= ^((chore|build)(\(deps(?:-dev)*\))*:) bump [^\s]+ from ([1-9][\d]*)\..+ to \4\.
#    actions:
#      update: {}
#      queue:
#        name: bots

#  - name: Automatically merge Crowdin PRs (only if all checks pass)
#    conditions:
#      - author = github-actions[bot]
#      - title ~= (new translations|update translations progress)
#    actions:
#      update: {}
#      queue:
#        name: bots

queue_rules:
  - name: bots
    merge_conditions:
      - -draft
      - check-success = "build / Lint and test"
      - check-success = "build / build (ubuntu-latest)"
      - check-success = "build / build (macos-latest)"
      - check-success = "build / build (windows-latest)"
      - or:
          - and: # translations
              - or:
                  - author = github-actions[bot]
                  - author = sircharlo
              - title ~= (new translations|update translations progress)
          - and: # dependabot
              - author = dependabot[bot]
              - or:
                  - title ~= ^((chore|build)(\(deps(?:-dev)*\))*:) bump [^\s]+ from ([1-9][\d]*)\..+ 
                    to \4\.
                  - title ~= ^((chore|build)(\(deps(-dev)?\))?:) bump the .+ group across .+ updates
merge_protections_settings:
  auto_merge: true
  reporting_method: check-runs
