pull_request_rules:
  - name: Automatic merge for trusted authors and dependabot
    conditions:
      - or:
          - author=mtdvlpr
          - author=sircharlo
          - and:
              - author=dependabot[bot]
              - or:
                 - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
                 - title~=^chore\(deps\). bump [^\s]+ from ([\d]+)\..+ to \1\.
                 - title~=^chore\(deps-dev\). bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      update:
      merge:
        method: squash
