pull_request_rules:
  - name: Automatically merge Dependabot PRs (only if all checks pass)
    conditions:
      - and:
          - or:
              - author = dependabot[bot]
              - author = github-actions[bot]
          - title ~= ^((chore|build)(\(deps(?:-dev)*\))*:) bump [^\s]+ from ([1-9][\d]*)\..+ to \4\.
          - check-success = *
    actions:
      update:
        bot_account: github-actions[bot]
      merge:
        method: squash
        strict: smart     # Rebase before merging if necessary
        strict_method: rebase
      delete_head_branch: true  # Delete branch after successful merge

  - name: Automatically merge Crowdin PRs (only if all checks pass)
    conditions:
      - and:
          - or:
              - author = sircharlo
              - author = github-actions[bot]
          - title ~= (new translations|update translations progress)
          - check-success = *
    actions:
      update:
        bot_account: github-actions[bot]
      merge:
        method: squash
        strict: smart
        strict_method: rebase
      delete_head_branch: true
