pull_request_rules:
  - name: Automatically merge Dependabot PRs (minor/patch only, including -dev and prereleases)
    conditions:
      - and:
          - or:
              - author = dependabot[bot]
              - author = github-actions[bot]
          # Matches "chore(deps): bump package from 1.2.3 to 1.3.0"
          # Handles optional -dev and prerelease tags (1.2.3-alpha.1)
          - title ~= ^((chore|build)(\(deps(?:-dev)*\))*:) bump [^\s]+ from ([1-9][\d]*)\..+ to \4\.
          - check-success = "build / lint"
          - check-success = "build / test"
          - check-success = "build / build (ubuntu-latest)"
          - check-success = "build / build (macos-latest)"
          - check-success = "build / build (macos-15-intel)"
          - check-success = "build / build (windows-latest)"
    actions:
      update: {}
      merge:
        method: squash

  - name: Automatically merge Crowdin PRs (only if all checks pass)
    conditions:
      - and:
          - or:
              - author = sircharlo
              - author = github-actions[bot]
          - title ~= (new translations|update translations progress)
          - check-success = "build / lint"
          - check-success = "build / test"
          - check-success = "build / build (ubuntu-latest)"
          - check-success = "build / build (macos-latest)"
          - check-success = "build / build (macos-15-intel)"
          - check-success = "build / build (windows-latest)"
    actions:
      update: {}
      merge:
        method: squash
