pull_request_rules:
  - name: Auto-merge translations (no CI required)
    conditions:
      - -draft
      - or:
          - author = github-actions[bot]
          - author = sircharlo
      - title ~= (new translations|update translations progress)
      - -files ~= ^(?!.*\.(md|json)$)  # no files outside .md and .json
    actions:
      queue:
        name: translations

  - name: Default queue (with CI)
    conditions:
      - -draft
      - not: title ~= (new translations|update translations progress)
      - or:
          - author = dependabot[bot]
          - author = github-actions[bot]
    actions:
      queue:
        name: bots

queue_rules:
  - name: translations
    merge_conditions:
      - -draft
      # 🚫 no build checks here

  - name: bots
    merge_conditions:
      - -draft
      - or:
          - check-success = "build / Lint and test"
          - check-neutral = "build / Lint and test"
          - check-skipped = "build / Lint and test"
      - or:
          - check-success = "build / build (ubuntu-latest)"
          - check-neutral = "build / build (ubuntu-latest)"
          - check-skipped = "build / build (ubuntu-latest)"
      - or:
          - check-success = "build / build (macos-latest)"
          - check-neutral = "build / build (macos-latest)"
          - check-skipped = "build / build (macos-latest)"
      - or:
          - check-success = "build / build (windows-latest)"
          - check-neutral = "build / build (windows-latest)"
          - check-skipped = "build / build (windows-latest)"
      - and: # dependabot
          - author = dependabot[bot]
          - or:
             - title ~= ^((chore|build)(\(deps(?:-dev)*\))*:) bump [^\s]+ from ([1-9][\d]*)\..+ to \4\.
             - title ~= ^((chore|build)(\(deps(-dev)?\))?:) bump the .+ group across .+ updates

merge_protections_settings:
  auto_merge: true
  reporting_method: check-runs
