pull_request_title: "chore: new translations"
files:
  - source: /_data/en.json
    translation: /_data/%two_letters_code%.json
  - source: /locales/en/index.md
    translation: /locales/%two_letters_code%/index.md
  - source: /locales/en/_posts/*
    translation: /locales/%two_letters_code%/_posts/%original_file_name%
