project_id: '559843'
pull_request_title: 'feat: new translations'
pull_request_labels:
  - translations
commit_message: 'feat: new translations for %language%'
append_commit_message: false
files:
  - source: /src/i18n/en.json
    translation: /src/i18n/%two_letters_code%.json
  - source: /src/release_notes/en/**
    translation: /src/release_notes/%two_letters_code%/%original_file_name%
  - source: /docs/src/en/**
    translation: /docs/src/%two_letters_code%/%original_file_name%
  - source: /docs/locales/en.json
    translation: /docs/locales/%two_letters_code%.json
