project_id: "559843"
pull_request_title: "chore: new translations"
commit_message: "chore: new translations for %language%"
append_commit_message: false
files:
  - source: /src/renderer/locales/en.json
    translation: /src/renderer/locales/%two_letters_code%.json
