sonar.projectKey=sircharlo_meeting-media-manager
sonar.organization=sircharlo
sonar.python.version=3.12
sonar.typescript.tsconfigPaths=tsconfig.sonar.json
sonar.exclusions=**/*.png,**/*.bmp,.yarn/**,**/__tests__/**,**/*.test.ts,**/*.test.mts,test/**
sonar.tests=src,src-electron,docs,test
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.mts,test/**
