title: '[Idea]: <title>'
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        ### Please read the following:
        Thanks for taking the time to fill out this idea form!

        Before submitting an idea, please make sure you have read the <a href="https://sircharlo.github.io/meeting-media-manager/" target="_blank">documentation website</a> and searched through the existing <a href="https://github.com/sircharlo/meeting-media-manager/issues" target="_blank">issues</a> and <a href="https://github.com/sircharlo/meeting-media-manager/discussions" target="_blank">discussions</a> to make sure your idea is not a duplicate.

        If your idea is still valid, please change the title of this discussion to reflect your idea and fill out the fields below.
  - type: textarea
    id: related-problem
    attributes:
      label: Is your idea related to a problem?
      description: Please describe.
      placeholder: I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe your idea
      description: A clear and concise description of what you want
      placeholder: I want this to be possible...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I tried this, but it didn't work because...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about your idea here.
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmations
      options:
        - label: I confirm that I have read the documentation website.
          required: true
        - label: I confirm that I have searched through the existing issues to make sure my idea is not a duplicate.
          required: true
        - label: I confirm that I have searched through the existing discussions to make sure my idea is not a duplicate.
          required: true
