title: '[Idea]: <title>'
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this idea form!
  - type: textarea
    id: related-problem
    attributes:
      label: Is your idea related to a problem?
      description: Please describe.
      placeholder: I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe your idea
      description: A clear and concise description of what you want
      placeholder: I want this to be possible...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I tried this, but it didn't work because...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
