title: '[Question]: <title>'
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        ### Please read the following:
        Thanks for taking the time to fill out this question form!

        Before submitting a question, please make sure you have read the [documentation website](https://sircharlo.github.io/meeting-media-manager/) and searched through the existing [issues](https://github.com/sircharlo/meeting-media-manager/issues?q=is%3Aissue+label%3Aquestion) and [discussions](https://github.com/sircharlo/meeting-media-manager/discussions/categories/q-a?discussions_q=) to make sure your question is not a duplicate.

        If your question is still valid, please change the title of this discussion to reflect your question and fill out the fields below.
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: A clear and concise question that you want to ask.
      placeholder: What? Why? How? When? Where? Who?
    validations:
      required: true
  - type: textarea
    id: related-problem
    attributes:
      label: Is your question related to a problem?
      description: Please describe.
      placeholder: I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about your question here.
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmations
      options:
        - label: I confirm that I have read the documentation website.
          required: true
        - label: I confirm that I have searched through the existing discussions to make sure my question is not a duplicate.
          required: true
