title: 'New translation in <language>'
labels: translations
body:
  - type: markdown
    attributes:
      value: |
        ### Please read the following:
        Thanks for taking the time to fill out this translations form!
        Please change the title of this discussion to reflect your language and fill out the fields below.
  - type: textarea
    id: language
    attributes:
      label: What language do you speak?
      description: |
        Try to include the native name, English name, JW code and lang code. [See full list of JW languages](https://www.jw.org/en/languages).
        For example: Nederlands/Dutch - O/nl
      placeholder: I would like to help translate M³ into ...
      value: I would like to help translate M³ into ...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Anything else you'd like to add?
