import type { SettingsGroups, SettingsItems, SettingsValues } from 'src/types';

import { CUSTOM_MEDIA_SECTIONS_ID } from 'src/constants/media';

// Enum Types
export const RESOLUTIONS = ['240p', '360p', '480p', '720p', '1080p'] as const;

/* eslint-disable perfectionist/sort-objects */
export const settingsGroups: SettingsGroups = {
  app: {
    description: 'applicationConfigurationDescription',
    icon: 'mmm-configuration',
    name: 'applicationConfiguration',
  },
  congregationMeetings: {
    description: 'congregationMeetingsDescription',
    icon: 'mmm-lectern',
    name: 'congregationMeetings',
  },
  mediaRetrievalPlayback: {
    description: 'mediaRetrievalAndPlaybackDescription',
    icon: 'mmm-media-settings',
    name: 'mediaRetrievalAndPlayback',
  },
  meetingTimer: {
    description: 'meetingTimerDescription',
    icon: 'mmm-time',
    name: 'meetingTimer',
  },
  integrations: {
    description: 'integrationsDescription',
    icon: 'mmm-integrations',
    name: 'integrations',
  },
  interfaceShortcuts: {
    description: 'interfaceShortcutsDescription',
    icon: 'mmm-keyboard',
    name: 'interfaceShortcuts',
  },
  advanced: {
    description: 'advancedDescription',
    icon: 'mmm-advanced-settings',
    name: 'advanced',
  },
};

export const settingsDefinitions: SettingsItems = {
  // App
  localAppLang: {
    group: 'app',
    list: 'appLanguages',
    rules: ['notEmpty'],
    subgroup: 'display',
    type: 'list',
  },
  localDateFormat: {
    group: 'app',
    subgroup: 'display',
    type: 'text',
  },
  darkMode: {
    group: 'app',
    list: 'darkModes',
    rules: ['notEmpty'],
    subgroup: 'display',
    type: 'list',
  },
  firstDayOfWeek: {
    group: 'app',
    list: 'days',
    subgroup: 'display',
    type: 'list',
  },
  autoStartAtLogin: {
    group: 'app',
    subgroup: 'startup',
    type: 'toggle',
  },
  // Congregation Meetings
  congregationName: {
    group: 'congregationMeetings',
    rules: ['notEmpty'],
    subgroup: 'congregationIdentity',
    type: 'text',
  },
  congregationNameModified: {
    group: 'congregationMeetings',
    hidden: true,
    subgroup: 'congregationIdentity',
    type: 'toggle',
  },
  relinkCongregationButton: {
    actions: ['openCongregationLookup'],
    depends: 'congregationNameModified',
    group: 'congregationMeetings',
    subgroup: 'congregationIdentity',
    type: 'button',
  },
  lang: {
    group: 'congregationMeetings',
    list: 'jwLanguages',
    rules: ['notEmpty'],
    subgroup: 'language',
    type: 'list',
  },
  langFallback: {
    group: 'congregationMeetings',
    list: 'jwLanguages',
    subgroup: 'language',
    type: 'list',
  },
  mwDay: {
    group: 'congregationMeetings',
    list: 'days',
    rules: ['notEmpty', 'regular'],
    subgroup: 'meetingSchedule',
    type: 'list',
    unless: 'disableMediaFetching',
  },
  mwStartTime: {
    group: 'congregationMeetings',
    options: ['meetingTime'],
    rules: ['notEmpty', 'regular'],
    subgroup: 'meetingSchedule',
    type: 'time',
    unless: 'disableMediaFetching',
  },
  weDay: {
    group: 'congregationMeetings',
    list: 'days',
    rules: ['notEmpty', 'regular'],
    subgroup: 'meetingSchedule',
    type: 'list',
    unless: 'disableMediaFetching',
  },
  weStartTime: {
    group: 'congregationMeetings',
    options: ['meetingTime'],
    rules: ['notEmpty', 'regular'],
    subgroup: 'meetingSchedule',
    type: 'time',
    unless: 'disableMediaFetching',
  },
  coWeek: {
    group: 'congregationMeetings',
    options: ['coTuesdays'],
    subgroup: 'specialDates',
    type: 'date',
    unless: 'disableMediaFetching',
  },
  memorialDate: {
    group: 'congregationMeetings',
    type: 'date',
    beta: false,
    options: ['futureDate'],
    subgroup: 'specialDates',
    unless: 'disableMediaFetching',
  },
  meetingScheduleChangeDate: {
    group: 'congregationMeetings',
    type: 'date',
    options: ['futureDate'],
    subgroup: 'meetingScheduleChange',
    unless: 'disableMediaFetching',
  },
  meetingScheduleChangeOnce: {
    group: 'congregationMeetings',
    depends: 'meetingScheduleChangeDate',
    subgroup: 'meetingScheduleChange',
    type: 'toggle',
    unless: 'disableMediaFetching',
  },
  meetingScheduleChangeMwDay: {
    group: 'congregationMeetings',
    depends: 'meetingScheduleChangeDate',
    list: 'days',
    rules: ['regular'],
    subgroup: 'meetingScheduleChange',
    type: 'list',
    unless: 'disableMediaFetching',
  },
  meetingScheduleChangeMwStartTime: {
    group: 'congregationMeetings',
    depends: 'meetingScheduleChangeDate',
    options: ['meetingTime'],
    rules: ['regular'],
    subgroup: 'meetingScheduleChange',
    type: 'time',
    unless: 'disableMediaFetching',
  },
  meetingScheduleChangeWeDay: {
    group: 'congregationMeetings',
    depends: 'meetingScheduleChangeDate',
    list: 'days',
    rules: ['regular'],
    subgroup: 'meetingScheduleChange',
    type: 'list',
    unless: 'disableMediaFetching',
  },
  meetingScheduleChangeWeStartTime: {
    group: 'congregationMeetings',
    depends: 'meetingScheduleChangeDate',
    options: ['meetingTime'],
    rules: ['regular'],
    subgroup: 'meetingScheduleChange',
    type: 'time',
    unless: 'disableMediaFetching',
  },
  enableAutomaticMeetingScheduleUpdates: {
    group: 'congregationMeetings',
    subgroup: 'meetingScheduleChange',
    type: 'toggle',
    unless: ['congregationNameModified', 'disableMediaFetching'],
  },
  reSyncMeetingScheduleButton: {
    actions: ['syncMeetingSchedule'],
    depends: 'enableAutomaticMeetingScheduleUpdates',
    group: 'congregationMeetings',
    subgroup: 'meetingScheduleChange',
    type: 'button',
    unless: ['disableMediaFetching', 'congregationNameModified'],
  },
  // Media Retrieval and Playback
  meteredConnection: {
    group: 'mediaRetrievalPlayback',
    subgroup: 'playback',
    type: 'toggle',
  },
  enableMediaDisplayButton: {
    group: 'mediaRetrievalPlayback',
    subgroup: 'playback',
    type: 'toggle',
  },
  enableMediaPreview: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'playback',
    type: 'toggle',
  },
  beginPlaybackPaused: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'playback',
    type: 'toggle',
  },
  enableMediaWindowFadeTransitions: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'media-display',
    type: 'toggle',
  },
  enablePlaybackSpeedControl: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'media-display',
    type: 'toggle',
  },
  hideMediaLogo: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'media-display',
    type: 'toggle',
  },
  maxRes: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    list: 'resolutions',
    rules: ['notEmpty'],
    subgroup: 'media-display',
    type: 'list',
  },
  includePrinted: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'media-display',
    type: 'toggle',
  },
  excludeWtParagraphVideos: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'media-display',
    type: 'toggle',
  },
  excludeCbsPubs: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'media-display',
    type: 'pubSymbols',
  },
  excludeFootnotes: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'media-display',
    type: 'toggle',
  },
  excludeTh: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'media-display',
    type: 'toggle',
  },
  enableMusicButton: {
    group: 'mediaRetrievalPlayback',
    subgroup: 'setupWizard.backgroundMusic',
    type: 'toggle',
  },
  autoStartMusic: {
    depends: 'enableMusicButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'setupWizard.backgroundMusic',
    type: 'toggle',
    unless: 'disableMediaFetching',
  },
  meetingStopBufferSeconds: {
    depends: 'enableMusicButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'setupWizard.backgroundMusic',
    type: 'slider',
    min: 0,
    max: 300,
    step: 5,
    unless: 'disableMediaFetching',
  },
  musicVolume: {
    actions: ['setBackgroundMusicVolume'],
    depends: 'enableMusicButton',
    group: 'mediaRetrievalPlayback',
    max: 100,
    min: 1,
    step: 1,
    subgroup: 'setupWizard.backgroundMusic',
    type: 'slider',
  },
  enableSubtitles: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'subtitles',
    type: 'toggle',
  },
  langSubtitles: {
    depends: 'enableSubtitles',
    group: 'mediaRetrievalPlayback',
    list: 'jwLanguages',
    subgroup: 'subtitles',
    type: 'list',
  },
  enableExtraCache: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'cache',
    type: 'toggle',
    unless: 'disableMediaFetching',
  },
  cacheFolder: {
    group: 'mediaRetrievalPlayback',
    subgroup: 'cache',
    type: 'path',
  },
  enableCacheAutoClear: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'cache',
    type: 'toggle',
    unless: 'disableMediaFetching',
  },
  enablePinyinSongs: {
    group: 'mediaRetrievalPlayback',
    subgroup: 'pinyin',
    type: 'toggle',
  },
  pinyinSongFolder: {
    group: 'mediaRetrievalPlayback',
    subgroup: 'pinyin',
    type: 'path',
  },
  enableMediaAutoExport: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'mediaExport',
    type: 'toggle',
    unless: 'disableMediaFetching',
  },
  mediaAutoExportFolder: {
    depends: ['enableMediaDisplayButton', 'enableMediaAutoExport'],
    group: 'mediaRetrievalPlayback',
    rules: ['notEmpty'],
    subgroup: 'mediaExport',
    type: 'path',
    unless: 'disableMediaFetching',
  },
  convertFilesToMp4: {
    depends: ['enableMediaDisplayButton', 'enableMediaAutoExport'],
    group: 'mediaRetrievalPlayback',
    subgroup: 'mediaExport',
    type: 'toggle',
    unless: 'disableMediaFetching',
  },
  enableFolderWatcher: {
    depends: 'enableMediaDisplayButton',
    group: 'mediaRetrievalPlayback',
    subgroup: 'folderWatcher',
    type: 'toggle',
  },
  folderToWatch: {
    depends: ['enableFolderWatcher', 'enableMediaDisplayButton'],
    group: 'mediaRetrievalPlayback',
    subgroup: 'folderWatcher',
    type: 'path',
  },

  // Meeting Timer
  enableTimerDisplay: {
    group: 'meetingTimer',
    beta: true,
    subgroup: 'timerDisplay',
    type: 'toggle',
  },
  timerAutoOpen: {
    depends: 'enableTimerDisplay',
    group: 'meetingTimer',
    subgroup: 'timerDisplay',
    type: 'toggle',
  },
  timerMode: {
    depends: 'enableTimerDisplay',
    group: 'meetingTimer',
    list: 'timerModes',
    rules: ['notEmpty'],
    subgroup: 'timerDisplay',
    type: 'list',
  },
  timerTimeOfDayDisplay: {
    depends: 'enableTimerDisplay',
    group: 'meetingTimer',
    list: 'timerDisplayFormats',
    rules: ['notEmpty'],
    subgroup: 'timerDisplay',
    type: 'list',
  },
  timerCountdownDisplay: {
    depends: 'enableTimerDisplay',
    group: 'meetingTimer',
    list: 'timerDisplayFormats',
    rules: ['notEmpty'],
    subgroup: 'timerDisplay',
    type: 'list',
  },
  timerHourFormat: {
    depends: 'enableTimerDisplay',
    group: 'meetingTimer',
    list: 'timerHourFormats',
    rules: ['notEmpty'],
    subgroup: 'timerDisplay',
    type: 'list',
  },
  timerShowOnActionIsland: {
    depends: 'enableTimerDisplay',
    group: 'meetingTimer',
    subgroup: 'timerDisplay',
    type: 'toggle',
  },
  timerEnableMeetingCountdown: {
    depends: 'enableTimerDisplay',
    group: 'meetingTimer',
    subgroup: 'timerCountdown',
    type: 'toggle',
  },
  timerMeetingCountdownMinutes: {
    depends: ['enableTimerDisplay', 'timerEnableMeetingCountdown'],
    group: 'meetingTimer',
    max: 10,
    min: 1,
    step: 1,
    subgroup: 'timerCountdown',
    type: 'slider',
  },
  timerCountdownWarningIndicator: {
    depends: ['enableTimerDisplay', 'timerCountdownDisplay'],
    group: 'meetingTimer',
    subgroup: 'timerCountdown',
    type: 'toggle',
  },
  timerOvertimeIndicator: {
    depends: ['enableTimerDisplay', 'timerMode'],
    group: 'meetingTimer',
    subgroup: 'timerCountdown',
    type: 'toggle',
  },
  timerOvertimeAnimation: {
    depends: ['enableTimerDisplay', 'timerOvertimeIndicator'],
    group: 'meetingTimer',
    subgroup: 'timerCountdown',
    type: 'toggle',
  },
  timerOvertimeShowAmountOnly: {
    depends: ['enableTimerDisplay', 'timerOvertimeIndicator'],
    group: 'meetingTimer',
    subgroup: 'timerCountdown',
    type: 'toggle',
  },
  timerEnableMeetingAheadBehind: {
    depends: ['enableTimerDisplay'],
    group: 'meetingTimer',
    subgroup: 'timerCountdown',
    type: 'toggle',
  },
  timerBackgroundColor: {
    group: 'meetingTimer',
    rules: ['notEmpty'],
    depends: 'enableTimerDisplay',
    subgroup: 'timerColors',
    type: 'color',
  },
  timerTextColor: {
    depends: 'enableTimerDisplay',
    rules: ['notEmpty'],
    group: 'meetingTimer',
    subgroup: 'timerColors',
    type: 'color',
  },
  timerTextSize: {
    depends: 'enableTimerDisplay',
    rules: ['notEmpty'],
    group: 'meetingTimer',
    subgroup: 'timerColors',
    list: 'fontSizes',
    type: 'list',
  },
  timerOvertimeBackgroundColor: {
    depends: ['enableTimerDisplay', 'timerOvertimeIndicator'],
    rules: ['notEmpty'],
    group: 'meetingTimer',
    subgroup: 'timerColors',
    type: 'color',
  },
  timerOvertimeTextColor: {
    depends: ['enableTimerDisplay', 'timerOvertimeIndicator'],
    rules: ['notEmpty'],
    group: 'meetingTimer',
    subgroup: 'timerColors',
    type: 'color',
  },

  // Integrations
  zoomEnable: {
    group: 'integrations',
    subgroup: 'zoomIntegration',
    type: 'toggle',
  },
  zoomScreenShareShortcut: {
    depends: 'zoomEnable',
    group: 'integrations',
    rules: ['notEmpty'],
    subgroup: 'zoomIntegration',
    type: 'shortcut',
  },
  zoomAutoFocusMediaWindow: {
    depends: 'zoomEnable',
    group: 'integrations',
    subgroup: 'zoomIntegration',
    type: 'toggle',
  },
  obsEnable: {
    actions: ['obsConnect'],
    group: 'integrations',
    subgroup: 'obsStudio',
    type: 'toggle',
  },
  obsPassword: {
    actions: ['obsConnect'],
    depends: 'obsEnable',
    group: 'integrations',
    subgroup: 'obsStudio',
    type: 'text',
  },
  obsPort: {
    actions: ['obsConnect'],
    depends: 'obsEnable',
    group: 'integrations',
    rules: ['portNumber'],
    subgroup: 'obsStudio',
    type: 'text',
  },
  obsCameraScene: {
    depends: ['obsEnable', 'obsPort', 'obsPassword'],
    group: 'integrations',
    list: 'obsAllScenes',
    subgroup: 'obsStudio',
    type: 'list',
  },
  obsMediaScene: {
    depends: ['obsEnable', 'obsPort', 'obsPassword'],
    group: 'integrations',
    list: 'obsAllScenes',
    subgroup: 'obsStudio',
    type: 'list',
  },
  obsImageScene: {
    depends: ['obsEnable', 'obsPort', 'obsPassword', 'obsMediaScene'],
    group: 'integrations',
    list: 'obsAllScenes',
    subgroup: 'obsStudio',
    type: 'list',
  },
  obsPostponeImages: {
    depends: ['obsEnable', 'obsPort', 'obsPassword', 'obsMediaScene'],
    group: 'integrations',
    subgroup: 'obsStudio',
    type: 'toggle',
  },
  obsQuickToggle: {
    depends: ['obsEnable', 'obsPort', 'obsPassword', 'obsMediaScene'],
    group: 'integrations',
    subgroup: 'obsStudio',
    type: 'toggle',
  },
  obsSwitchSceneAfterMedia: {
    depends: ['obsEnable', 'obsPort', 'obsPassword', 'obsMediaScene'],
    group: 'integrations',
    subgroup: 'obsStudio',
    type: 'toggle',
  },
  obsRememberPreviouslyUsedScene: {
    depends: [
      'obsEnable',
      'obsPort',
      'obsPassword',
      'obsMediaScene',
      'obsCameraScene',
    ],
    group: 'integrations',
    subgroup: 'obsStudio',
    type: 'toggle',
  },
  obsHideIcons: {
    depends: ['obsEnable', 'obsPort', 'obsPassword'],
    group: 'integrations',
    subgroup: 'obsStudio',
    type: 'toggle',
  },
  obsEnableRecordingControls: {
    depends: ['obsEnable', 'obsPort', 'obsPassword'],
    group: 'integrations',
    subgroup: 'obsStudio',
    type: 'toggle',
  },
  enableCustomEvents: {
    group: 'integrations',
    subgroup: 'customEvents',
    type: 'toggle',
  },
  customEventMediaPlayShortcut: {
    depends: 'enableCustomEvents',
    group: 'integrations',
    subgroup: 'customEvents',
    type: 'shortcut',
  },
  customEventMediaPauseShortcut: {
    depends: 'enableCustomEvents',
    group: 'integrations',
    subgroup: 'customEvents',
    type: 'shortcut',
  },
  customEventMediaStopShortcut: {
    depends: 'enableCustomEvents',
    group: 'integrations',
    subgroup: 'customEvents',
    type: 'shortcut',
  },
  customEventLastSongShortcut: {
    depends: 'enableCustomEvents',
    group: 'integrations',
    subgroup: 'customEvents',
    type: 'shortcut',
  },

  // Meeting Recording
  recordingEnable: {
    group: 'integrations',
    subgroup: 'meetingRecording',
    type: 'toggle',
    unless: 'obsEnableRecordingControls',
  },
  recordingStartShortcut: {
    depends: 'recordingEnable',
    group: 'integrations',
    rules: ['notEmpty'],
    subgroup: 'meetingRecording',
    type: 'shortcut',
    unless: 'obsEnableRecordingControls',
  },
  recordingStopShortcut: {
    depends: ['recordingEnable', 'recordingStartShortcut'],
    group: 'integrations',
    subgroup: 'meetingRecording',
    type: 'shortcut',
    unless: 'obsEnableRecordingControls',
  },
  recordingFolder: {
    depends: ['recordingEnable', 'recordingStartShortcut'],
    group: 'integrations',
    subgroup: 'meetingRecording',
    type: 'path',
    unless: 'obsEnableRecordingControls',
  },

  // Interface & Shortcuts
  enableKeyboardShortcuts: {
    group: 'interfaceShortcuts',
    subgroup: 'keyboardShortcuts',
    type: 'toggle',
  },
  shortcutMediaWindow: {
    depends: 'enableKeyboardShortcuts',
    group: 'interfaceShortcuts',
    subgroup: 'keyboardShortcuts',
    type: 'shortcut',
  },
  shortcutMediaPrevious: {
    depends: 'enableKeyboardShortcuts',
    group: 'interfaceShortcuts',
    subgroup: 'keyboardShortcuts',
    type: 'shortcut',
  },
  shortcutMediaNext: {
    depends: 'enableKeyboardShortcuts',
    group: 'interfaceShortcuts',
    subgroup: 'keyboardShortcuts',
    type: 'shortcut',
  },
  shortcutMediaPauseResume: {
    depends: 'enableKeyboardShortcuts',
    group: 'interfaceShortcuts',
    subgroup: 'keyboardShortcuts',
    type: 'shortcut',
  },
  shortcutMediaStop: {
    depends: 'enableKeyboardShortcuts',
    group: 'interfaceShortcuts',
    subgroup: 'keyboardShortcuts',
    type: 'shortcut',
  },
  shortcutMusic: {
    depends: 'enableKeyboardShortcuts',
    group: 'interfaceShortcuts',
    subgroup: 'keyboardShortcuts',
    type: 'shortcut',
  },
  addMediaButtonSections: {
    group: 'interfaceShortcuts',
    subgroup: 'addMediaButton',
    type: 'mediaSections',
  },
  compactAddMediaButton: {
    group: 'interfaceShortcuts',
    subgroup: 'addMediaButton',
    type: 'toggle',
  },
  showMediaDragHandle: {
    group: 'interfaceShortcuts',
    subgroup: 'dragAndDrop',
    type: 'toggle',
  },
  // The toggle and the checklist/category arrays are all rendered by
  // SettingsMeetingChecklists.vue (a hand-written editor, not BaseInput) so
  // they read as one consistently-styled settings card instead of the
  // toggle getting its own separate auto-rendered card - hidden here purely
  // to satisfy the SettingsValues → SettingsItems type constraint.
  enableMeetingQuickActions: {
    group: 'interfaceShortcuts',
    hidden: true,
    subgroup: 'quickActions',
    type: 'toggle',
  },
  meetingQuickActionsCategoriesAfter: {
    group: 'interfaceShortcuts',
    hidden: true,
    subgroup: 'quickActions',
    type: 'text',
  },
  meetingQuickActionsCategoriesBefore: {
    group: 'interfaceShortcuts',
    hidden: true,
    subgroup: 'quickActions',
    type: 'text',
  },
  meetingQuickActionsChecklistAfter: {
    group: 'interfaceShortcuts',
    hidden: true,
    subgroup: 'quickActions',
    type: 'text',
  },
  meetingQuickActionsChecklistBefore: {
    group: 'interfaceShortcuts',
    hidden: true,
    subgroup: 'quickActions',
    type: 'text',
  },

  // Advanced
  baseUrl: {
    rules: ['notEmpty'],
    group: 'advanced',
    subgroup: 'dangerZone',
    type: 'text',
  },
  disableMediaFetching: {
    group: 'advanced',
    subgroup: 'dangerZone',
    type: 'toggle',
  },
  disableHardwareAcceleration: {
    group: 'advanced',
    subgroup: 'dangerZone',
    type: 'toggle',
  },
  suppressHardwareAccelerationReminder: {
    group: 'advanced',
    depends: 'disableHardwareAcceleration',
    subgroup: 'dangerZone',
    type: 'toggle',
  },
};
/* eslint-enable perfectionist/sort-objects */

export const defaultSettings: SettingsValues = {
  addMediaButtonSections: [
    'pt',
    'lac',
    'circuit-overseer',
    CUSTOM_MEDIA_SECTIONS_ID,
  ],
  autoStartAtLogin: false,
  autoStartMusic: true,
  baseUrl: 'jw.org',
  beginPlaybackPaused: false,
  cacheFolder: null,
  compactAddMediaButton: true,
  congregationName: null,
  congregationNameModified: true,
  convertFilesToMp4: false,
  coWeek: null,
  customEventLastSongShortcut: null,
  customEventMediaPauseShortcut: null,
  customEventMediaPlayShortcut: null,
  customEventMediaStopShortcut: null,
  darkMode: 'auto',
  disableHardwareAcceleration: false,
  disableMediaFetching: false,
  enableAutomaticMeetingScheduleUpdates: true,
  enableCacheAutoClear: true,
  enableCustomEvents: false,
  enableExtraCache: false,
  enableFolderWatcher: false,
  enableKeyboardShortcuts: false,
  enableMediaAutoExport: false,
  enableMediaDisplayButton: false,
  enableMediaPreview: true,
  enableMediaWindowFadeTransitions: true,
  enableMeetingQuickActions: true,
  enableMusicButton: true,
  enablePinyinSongs: false,
  enablePlaybackSpeedControl: false,
  enableSubtitles: false,
  enableTimerDisplay: false,
  excludeCbsPubs: ['wcg'],
  excludeFootnotes: false,
  excludeTh: true,
  excludeWtParagraphVideos: false,
  firstDayOfWeek: 0,
  folderToWatch: '',
  hideMediaLogo: false,
  includePrinted: true,
  lang: 'E',
  langFallback: null,
  langSubtitles: null,
  localAppLang: 'en',
  localDateFormat: 'D MMMM YYYY',
  maxRes: '720p',
  mediaAutoExportFolder: '',
  meetingQuickActionsCategoriesAfter: [
    {
      enabled: true,
      id: 'quick-actions-category-zoom-participants',
      isDefault: true,
    },
    {
      enabled: true,
      id: 'quick-actions-category-kh-av',
      isDefault: true,
    },
  ],
  meetingQuickActionsCategoriesBefore: [
    {
      enabled: true,
      id: 'quick-actions-category-zoom-participants',
      isDefault: true,
    },
    {
      enabled: true,
      id: 'quick-actions-category-kh-av',
      isDefault: true,
    },
  ],
  meetingQuickActionsChecklistAfter: [
    {
      categoryId: 'quick-actions-category-kh-av',
      enabled: true,
      id: 'quick-actions-checklist-disconnect-zoom-audio',
      isDefault: true,
      label: undefined,
    },
    {
      categoryId: 'quick-actions-category-zoom-participants',
      enabled: true,
      id: 'quick-actions-checklist-unmute-zoom-participants',
      isDefault: true,
      label: undefined,
    },
    {
      categoryId: 'quick-actions-category-zoom-participants',
      enabled: true,
      id: 'quick-actions-checklist-allow-unmute-zoom-participants',
      isDefault: true,
      label: undefined,
    },
    {
      categoryId: 'quick-actions-category-kh-av',
      enabled: true,
      id: 'quick-actions-checklist-mute-kh-audio',
      isDefault: true,
      label: undefined,
    },
    {
      categoryId: 'quick-actions-category-kh-av',
      enabled: true,
      id: 'quick-actions-checklist-deactivate-kh-video',
      isDefault: true,
      label: undefined,
    },
  ],
  meetingQuickActionsChecklistBefore: [
    {
      categoryId: 'quick-actions-category-zoom-participants',
      enabled: true,
      id: 'quick-actions-checklist-mute-zoom-participants',
      isDefault: true,
      label: undefined,
    },
    {
      categoryId: 'quick-actions-category-zoom-participants',
      enabled: true,
      id: 'quick-actions-checklist-disallow-unmute-zoom-participants',
      isDefault: true,
      label: undefined,
    },
    {
      categoryId: 'quick-actions-category-kh-av',
      enabled: true,
      id: 'quick-actions-checklist-unmute-kh-audio',
      isDefault: true,
      label: undefined,
    },
    {
      categoryId: 'quick-actions-category-kh-av',
      enabled: true,
      id: 'quick-actions-checklist-activate-kh-video-zoom',
      isDefault: true,
      label: undefined,
    },
  ],
  meetingScheduleChangeDate: null,
  meetingScheduleChangeMwDay: null,
  meetingScheduleChangeMwStartTime: null,
  meetingScheduleChangeOnce: false,
  meetingScheduleChangeWeDay: null,
  meetingScheduleChangeWeStartTime: null,
  meetingStopBufferSeconds: 60,
  memorialDate: null,
  meteredConnection: false,
  musicVolume: 100,
  mwDay: null,
  mwStartTime: null,
  obsCameraScene: null,
  obsEnable: false,
  obsEnableRecordingControls: false,
  obsHideIcons: false,
  obsImageScene: null,
  obsMediaScene: null,
  obsPassword: null,
  obsPort: null,
  obsPostponeImages: false,
  obsQuickToggle: false,
  obsRememberPreviouslyUsedScene: true,
  obsSwitchSceneAfterMedia: false,
  pinyinSongFolder: null,
  recordingEnable: false,
  recordingFolder: null,
  recordingStartShortcut: null,
  recordingStopShortcut: null,
  relinkCongregationButton: false,
  reSyncMeetingScheduleButton: false,
  shortcutMediaNext: null,
  shortcutMediaPauseResume: null,
  shortcutMediaPrevious: null,
  shortcutMediaStop: null,
  shortcutMediaWindow: null,
  shortcutMusic: null,
  showMediaDragHandle: true,
  suppressHardwareAccelerationReminder: false,
  timerAutoOpen: false,
  timerBackgroundColor: '#000000',
  timerCountdownDisplay: 'digital',
  timerCountdownWarningIndicator: false,
  timerEnableMeetingAheadBehind: false,
  timerEnableMeetingCountdown: false,
  timerHourFormat: '24h',
  timerMeetingCountdownMinutes: 5,
  timerMode: 'countup',
  timerOvertimeAnimation: true,
  timerOvertimeBackgroundColor: '#000000',
  timerOvertimeIndicator: false,
  timerOvertimeShowAmountOnly: true,
  timerOvertimeTextColor: '#ff0000',
  timerShowOnActionIsland: false,
  timerTextColor: '#ffffff',
  timerTextSize: '10vw',
  timerTimeOfDayDisplay: 'digital',
  weDay: null,
  weStartTime: null,
  zoomAutoFocusMediaWindow: false,
  zoomEnable: false,
  zoomScreenShareShortcut: null,
};
