name: Bug Report
description: Create a report to help us improve
title: '[Bug]: <title>'
labels: ['bug']
assignees:
  - mtdvlpr
  - sircharlo
body:
  - type: markdown
    attributes:
      value: |
        ### Please read the following:
        Thanks for taking the time to fill out this bug report!

        Before submitting a bug report, please make sure you have read the [documentation website](https://sircharlo.github.io/meeting-media-manager/) and searched through the existing [issues](https://github.com/sircharlo/meeting-media-manager/issues) and [discussions](https://github.com/sircharlo/meeting-media-manager/discussions) to make sure your bug report is not a duplicate. If you're using macOS, please also make sure you have executed the Terminal commands found in the [additional steps for macOS users](https://sircharlo.github.io/meeting-media-manager/using-at-a-kingdom-hall#additional-steps-for-macos-users) section the documentation website.

        If your bug report is still valid, please change the title of this issue to reflect your bug report and fill out the fields below.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug.
      placeholder: When you do this, this happens...
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Do '....'
        4. See error
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Do '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: whats-expected
    attributes:
      label: What did you expect to happen?
      description: Describe what you expected to happen.
      placeholder: I expected this to happen...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        What version of M³ are you running?
        Click on the M³ logo in the top left corner of the app.
      placeholder: vXX.X.X
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing the problem on?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.
        To open the inspector, hit <kbd>Ctrl</kbd> <kbd>⇧ Shift</kbd> <kbd>I</kbd> (<kbd>⌘ Command</kbd> <kbd>⌥ Option</kbd> <kbd>I</kbd> for macOS) when the app is starting up.
      render: shell
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmations
      options:
        - label: I confirm that I have read the documentation website.
          required: true
        - label: I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
          required: true
        - label: I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.
          required: true
        - label: If I am using macOS, I confirm that I have executed the Terminal commands found in the "additional steps for macOS users" section of the documentation website.
          required: true
