name: Bug Report
description: Create a report to help us improve
title: '[Bug]: <title>'
labels: ['bug']
assignees:
  - mtdvlpr
  - sircharlo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug.
      placeholder: When you do this, this happens...
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Do '....'
        4. See error
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Do '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: whats-expected
    attributes:
      label: What did you expect to happen?
      description: Describe what you expected to happen.
      placeholder: I expected this to happen...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        What version of M³ are you running?
        You can find your version in the settings.
      placeholder: vXX.X.X
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing the problem on?
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.
        To open the inspector, hit <kbd>Ctrl</kbd> <kbd>⇧ Shift</kbd> <kbd>I</kbd> (<kbd>⌘ Command</kbd> <kbd>⌥ Option</kbd> <kbd>I</kbd> for Mac) when the app is starting up.
      render: shell
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
