blank_issues_enabled: false
contact_links:
  - name: Have you tried our documentation?
    url: https://sircharlo.github.io/meeting-media-manager/
    about: Please check our documentation before opening an issue.
  - name: Checked the documentation and/or just have a question?
    url: https://github.com/sircharlo/meeting-media-manager/discussions
    about: Please ask and answer questions in the discussions section.
