name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: <title>'
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        ### Please read the following:
        Thanks for taking the time to fill out this feature request!

        Before submitting a feature request, please make sure you have read the [documentation website](https://sircharlo.github.io/meeting-media-manager/) and searched through the existing [issues](https://github.com/sircharlo/meeting-media-manager/issues) and [discussions](https://github.com/sircharlo/meeting-media-manager/discussions) to make sure your feature request is not a duplicate.

        If your feature request is still valid, please change the title of this issue to reflect your feature request and fill out the fields below.
  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe.
      placeholder: I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I want this to be possible...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I tried this, but it didn't work because...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmations
      options:
        - label: I confirm that I have read the documentation website.
          required: true
        - label: I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
          required: true
        - label: I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.
          required: true
