name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: <title>'
labels: ['enhancement']
assignees:
  - mtdvlpr
  - sircharlo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe.
      placeholder: I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I want this to be possible...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I tried this, but it didn't work because...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
