name: Add Labels

on:
  pull_request:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'fix') }}
        with:
          labels: bug
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'feat') }}
        with:
          labels: enhancement
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'update deps') }}
        with:
          labels: |
            dependencies
            javascript
